Repository Couch-Coders/6th-camp_us-fe, pull requests merged in 2022-03, with the labels that each got.

#123 [#115]Feature/communityRoute 커뮤니티 페이지 UI
  src/App.js
  src/pages/communityPage/CommunityPage.jsx
  src/pages/communityPage/CommunityPage.style.js
  src/pages/communityPage/category/CommunityAllPost.js
  src/pages/communityPage/category/CommunityCategory.style.js
  src/pages/communityPage/category/CommunityPicture.js
  src/pages/communityPage/category/CommunityQnA.js
  src/pages/communityPage/category/CommunityTalk.js
  src/pages/communityPage/writePage/WritePage.jsx
Labels: enhancement

#122 [#112] Refactoring
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  package.json
  src/App.js
  src/assets/images/banner.webp
  src/common/addressData.js
  src/components/navbar/Navbar.jsx
  src/components/navbar/Navbar.styles.js
  src/components/resetRate/ResetRate.jsx
  src/components/skeleton/reviewSkeleton/reviewSkeleton.style.js
  src/context/CoordinateContext.js
  src/pages/mainPage/MainPage.jsx
  src/pages/mainPage/mainBestReview/mainBestReview.styles.js
  src/pages/mainPage/mainSearch/MainSearch.jsx
  src/pages/searchPage/SearchPage.jsx
  src/pages/searchPage/searchBar/SearchBar.jsx
  src/pages/searchPage/searchBar/resultList/ResultList.jsx
  src/pages/searchPage/searchBar/resultList/ResultList.style.js
  src/pages/searchPage/searchBar/searchBar.style.js
  src/pages/searchPage/searchBar/searchResult/searchResult/SearchResult.jsx
  src/pages/searchPage/searchLocation/SearchLocation.jsx
  src/service/api.js
  src/styles/globalStyle.js
Labels: enhancement, refactor

#119 [#111]mobileRefactoring 모바일 리팩토링
  public/index.html
  src/components/tag/Tag.style.js
  src/pages/detailPage/campLocation/CampLocation.jsx
  src/pages/searchPage/SearchPage.jsx
  src/pages/searchPage/searchBar/SearchBar.jsx
Labels: refactor

#125 GithubAction CI/CD Setting
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  public/index.html
  src/App.js
  src/assets/images/banner.webp
  src/common/addressData.js
  src/components/navbar/Navbar.jsx
  src/components/navbar/Navbar.styles.js
  src/components/resetRate/ResetRate.jsx
  src/components/skeleton/reviewSkeleton/reviewSkeleton.style.js
  src/components/tag/Tag.style.js
  src/context/CoordinateContext.js
  src/pages/communityPage/CommunityPage.jsx
  src/pages/communityPage/CommunityPage.style.js
  src/pages/communityPage/category/CommunityAllPost.js
  src/pages/communityPage/category/CommunityCategory.style.js
  src/pages/communityPage/category/CommunityPicture.js
  src/pages/communityPage/category/CommunityQnA.js
  src/pages/communityPage/category/CommunityTalk.js
  src/pages/communityPage/writePage/WritePage.jsx
  src/pages/detailPage/campLocation/CampLocation.jsx
  src/pages/mainPage/MainPage.jsx
  src/pages/mainPage/mainSearch/MainSearch.jsx
  src/pages/searchPage/SearchPage.jsx
  src/pages/searchPage/searchBar/SearchBar.jsx
  src/pages/searchPage/searchBar/resultList/ResultList.jsx
  src/pages/searchPage/searchBar/resultList/ResultList.style.js
  src/pages/searchPage/searchBar/searchBar.style.js
  src/pages/searchPage/searchBar/searchResult/searchResult/SearchResult.jsx
  src/pages/searchPage/searchLocation/SearchLocation.jsx
  src/service/api.js
  src/styles/globalStyle.js
Labels: enhancement

#128 fix: GithubAction npm deploy 대신 build로 변경하고 aws key 추가
  .github/workflows/deploy.yml
Labels: bug

#131 fix: Build시 Warning을 Error로 인식하는 에러 해결
  .github/workflows/deploy.yml
Labels: bug

#132 fix: ubuntu-latest에서 ubuntu-18.04로 번경
  .github/workflows/deploy.yml
Labels: bug

#135 fix: cloudfront cache 제거
  .github/workflows/deploy.yml
Labels: bug

#136 Develop
  .github/workflows/deploy.yml
Labels: bug

#137 fix: yml 파일 env 수정
  .github/workflows/deploy.yml
Labels: bug

#124 [#120] feature/searchListLike 검색페이지 검색결과 리스트 좋아요 기능 추가
  src/components/campLike/CampLike.jsx
  src/pages/searchPage/searchBar/SearchBar.jsx
  src/pages/searchPage/searchBar/resultList/ResultList.jsx
  src/pages/searchPage/searchBar/resultList/ResultList.style.js
  src/service/api.js
Labels: enhancement

#140 [#114]Feature/comment
  src/components/notice/Notice.jsx
  src/pages/communityPage/communityDetailPage/CommunityDetailPage.jsx
  src/pages/communityPage/communityDetailPage/postComments/PostComments.jsx
  src/pages/communityPage/communityDetailPage/postComments/PostComments.style.js
  src/pages/communityPage/communityDetailPage/postComments/commentList/CommentList.jsx
  src/pages/communityPage/communityDetailPage/postComments/commentList/CommentList.style.js
Labels: enhancement

#139 [#118] Feature/myPagePost
  src/components/notice/Notice.jsx
  src/components/skeleton/communityCommentSkeleton/CommunityCommentSkeleton.jsx
  src/components/skeleton/communityCommentSkeleton/CommunityCommentSkeleton.style.js
  src/components/skeleton/communityPostSkeleton/CommunityPostSkeleton.jsx
  src/components/skeleton/communityPostSkeleton/CommunityPostSkeleton.style.js
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPage.styles.js
  src/pages/myPage/myComments/MyCommentLayout.jsx
  src/pages/myPage/myComments/MyComments.jsx
  src/pages/myPage/myComments/MyComments.styles.js
  src/pages/myPage/myPostsList/MyPostLayout.jsx
  src/pages/myPage/myPostsList/MyPosts.jsx
  src/pages/myPage/myPostsList/MyPosts.styles.js
  src/styles/globalStyle.js
Labels: enhancement

#141 [#115] Feature/community 게시글 등록 페이지 UI 및 기능 구현
  package-lock.json
  package.json
  src/App.js
  src/components/imageUpload/ImageUpload.jsx
  src/components/postEditor/PostEditor.jsx
  src/components/review/Review.jsx
  src/components/review/reveiwList/ReviewsList.jsx
  src/pages/communityPage/category/CommunityAllPost.jsx
  src/pages/communityPage/category/CommunityPicture.jsx
  src/pages/communityPage/category/CommunityQnA.jsx
  src/pages/communityPage/category/CommunityTalk.jsx
  src/pages/communityPage/communityDetailPage/CommunityDetailPage.jsx
  src/pages/communityPage/communityDetailPage/communityDetailPage.style.js
  src/pages/communityPage/communityWritePage/CommunityWritePage.jsx
  src/pages/communityPage/communityWritePage/communityWritePage.style.js
  src/pages/communityPage/writePage/CommunityWritePage.jsx
  src/styles/globalStyle.js
Labels: enhancement

#143 [#142] feature/reset 검색페이지 검색내용 전체 초기화
  src/pages/searchPage/searchBar/SearchBar.jsx
  src/pages/searchPage/searchBar/searchBar.style.js
Labels: enhancement

#144 [#121] Feature/refreshToken Firebase 토큰 만료 이슈 해결
  src/components/auth/AuthProvider.js
  src/pages/searchPage/searchBar/SearchBar.jsx
Labels: bug, refactor

#145 [#115] Feature/community 게시글 등록, 조회, 삭제 기능 구현
  README.md
  package-lock.json
  package.json
  src/components/auth/AuthProvider.js
  src/components/auth/RegisterForm.js
  src/components/communityPost/CommunityPost.jsx
  src/components/communityPost/communityPost.style.js
  src/components/imageUpload/ImageUpload.jsx
  src/components/imageUpload/imageUpload.style.js
  src/components/modal/authModal/AuthModal.jsx
  src/components/modal/authModal/AuthModal.style.js
  src/components/modal/confirmModal/ConfirmModal.jsx
  src/components/modal/confirmModal/confirmModal.style.js
  src/components/navbar/Navbar.jsx
  src/components/postEditor/PostEditor.jsx
  src/components/review/reveiwList/ReviewsList.jsx
  src/components/skeleton/communityDetailSkeleton/CommunityDetailSkeleton.jsx
  src/components/skeleton/communityDetailSkeleton/communityDetailSkeleton.style.js
  src/pages/communityPage/CommunityPage.jsx
  src/pages/communityPage/category/CommunityAllPost.jsx
  src/pages/communityPage/category/CommunityCategory.jsx
  src/pages/communityPage/category/CommunityPicture.jsx
  src/pages/communityPage/category/CommunityQnA.jsx
  src/pages/communityPage/category/CommunityTalk.jsx
  src/pages/communityPage/communityDetailPage/CommunityDetailPage.jsx
  src/pages/communityPage/communityDetailPage/communityDetailPage.style.js
  src/pages/communityPage/communityDetailPage/postComments/PostComments.jsx
  src/pages/communityPage/communityDetailPage/postComments/commentList/CommentList.jsx
  src/pages/communityPage/communityWritePage/CommunityWritePage.jsx
  src/pages/communityPage/communityWritePage/communityWritePage.style.js
  src/pages/myPage/myComments/MyComments.jsx
  src/service/api.js
Labels: enhancement

#147 [#114]Feature/comment 커뮤니티 게시글 댓글
  src/pages/communityPage/communityDetailPage/CommunityDetailPage.jsx
  src/pages/communityPage/communityDetailPage/postComments/PostComments.jsx
  src/pages/communityPage/communityDetailPage/postComments/commentList/CommentList.jsx
  src/pages/communityPage/communityDetailPage/postComments/commentList/CommentList.style.js
  src/service/api.js
Labels: enhancement

#148 [#115 #117] Feature/community 게시글 좋아요, 베스트 게시글 기능 구현
  src/components/bestPost/BestPost.jsx
  src/components/bestPost/bestPost.style.js
  src/components/bestPost/bestPostSliderList/BestPostSliderList.jsx
  src/components/bestPost/bestPostSliderList/bestPostSliderList.style.js
  src/components/communityPost/CommunityPost.jsx
  src/components/communityPost/communityPost.style.js
  src/components/likeButton/LikeButton.jsx
  src/components/likeButton/likeButton.style.js
  src/components/skeleton/bestPostSkeleton/BestPostSkeleton.jsx
  src/components/skeleton/bestPostSkeleton/bestPostSkeleton.style.js
  src/components/skeleton/communityCommentSkeleton/CommunityCommentSkeleton.jsx
  src/pages/communityPage/category/CommunityCategory.jsx
  src/pages/communityPage/category/CommunityCategory.style.js
  src/pages/communityPage/communityDetailPage/CommunityDetailPage.jsx
  src/pages/communityPage/communityDetailPage/communityDetailPage.style.js
  src/pages/detailPage/DetailPage.jsx
  src/pages/mainPage/mainCampRecommend/nearCamp/NearCamp.jsx
  src/pages/searchPage/searchBar/resultList/ResultList.jsx
  src/service/api.js
Labels: enhancement, design

#151 [#150 #113] feat: 슬라이더에 회원이 좋아요한 게시글 좋아요 표시, 모달 OAuth 추가
  src/components/bestPost/bestPostSliderList/BestPostSliderList.jsx
  src/components/bestPost/bestPostSliderList/bestPostSliderList.style.js
  src/components/modal/authModal/AuthModal.jsx
  src/components/modal/authModal/AuthModal.style.js
  src/service/firebaseAuth.js
Labels: enhancement

#149 [#118]Feature/myPagePost 마이페이지 나의게시글, 나의 댓글, 알림
  src/components/postSetter/PostSetter.jsx
  src/pages/communityPage/communityEditPage/CommunityEditPage.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPage.styles.js
  src/pages/myPage/alrimList/AlrimLayout.jsx
  src/pages/myPage/alrimList/alrim/Alrim.jsx
  src/pages/myPage/alrimList/alrim/alrim.style.js
  src/pages/myPage/myComments/MyCommentLayout.jsx
  src/pages/myPage/myComments/MyComments.jsx
  src/pages/myPage/myComments/MyComments.styles.js
  src/pages/myPage/myPostsList/MyPostLayout.jsx
  src/pages/myPage/myPostsList/MyPosts.jsx
  src/pages/myPage/myPostsList/MyPosts.styles.js
  src/service/api.js
Labels: enhancement
