Repository Couch-Coders/6th-camp_us-fe, pull requests merged in 2022-02, with the labels that each got.

#25 [#18]feature/firebase Firebase Google OAuth 인증 구성 완료
  package-lock.json
  package.json
  src/App.js
  src/Components/Navbar/Navbar.js
  src/Components/auth/AuthProvider.js
  src/Components/auth/RegisterForm.js
  src/Service/firebaseAuth.js
Labels: enhancement

#26 [#18]feature/firebase OAuth 백엔드 연동 및 로그인, 회원가입 모달 추가
  cors.json
  package.json
  src/App.js
  src/Components/Modal/Modal.jsx
  src/Components/Modal/Modal.style.js
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/Navbar.styles.js
  src/Components/auth/AuthProvider.js
  src/Components/auth/RegisterForm.js
Labels: enhancement

#28 [#10]feature/searchPage/map 지도에 검색결과 표시 및 마커 클릭시 인포윈도우 렌더링
  json-server/db.json
  package-lock.json
  package.json
  src/Components/SearchLocation/EventMarker/EventMarker.jsx
  src/Components/SearchLocation/EventMarker/EventMarker.style.js
  src/Components/SearchLocation/SearchLocation.jsx
  src/Components/auth/AuthProvider.js
  src/Components/auth/RegisterForm.js
  src/Pages/SearchPage/SearchPage.js
  src/setupProxy.js
Labels: enhancement

#32 [#2]feature/main 검색영역 별점부분 수정
  src/Components/Main/MainSearch/MainSearch.js
Labels: enhancement

#34 [#9] feature/searchPage/search 검색페이지 검색 기능, 검색 결과 및 마커 등록
  json-server/db.json
  package-lock.json
  package.json
  src/Common/AddressData.js
  src/Common/category.js
  src/Components/CampInfoTag/CampInfoTag.jsx
  src/Components/CampInformation/CampInformation.jsx
  src/Components/Main/MainSearch/MainSearch.js
  src/Components/SearchBar/ResultList/ResultList.jsx
  src/Components/SearchBar/SearchBar.jsx
  src/Components/SearchBar/SearchBar.style.js
  src/Components/SearchBar/SearchResult/SearchResult.jsx
  src/Components/SearchLocation/EventMarker/EventMarker.jsx
  src/Components/SearchLocation/SearchLocation.jsx
  src/Components/Tag/Tag.jsx
  src/Components/Tag/Tag.style.js
  src/Components/auth/AuthProvider.js
  src/Components/index.js
  src/Pages/DetailPage/DetailPage.jsx
  src/Pages/SearchPage/SearchPage.js
  src/Service/camps.js
  src/Styles/GrobalStyle.js
  yarn.lock
Labels: enhancement

#27 [#11]feature/myPage/likeList 마이페이지 UI 및 좋아요 리스트
  json-server/db.json
  src/App.js
  src/Components/MyPage/AlrimList/AlrimList.js
  src/Components/MyPage/LikesList/LikeListLayout.js
  src/Components/MyPage/LikesList/LikesList.js
  src/Components/MyPage/LikesList/LikesList.styles.js
  src/Components/MyPage/MyReviews/MyReviews.js
  src/Components/Pagination/Pagination.js
  src/Components/Pagination/Pagination.style.js
  src/Pages/DetailPage/DetailPage.style.js
  src/Pages/MyPage/MyPage.js
  src/Pages/MyPage/MyPage.styles.js
  src/Service/camps.js
Labels: enhancement

#39 Feature/public favicon, Logo 및 index.html 수정
  json-server/db.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/Service/camps.js
  yarn.lock
Labels: enhancement

#41 [#13]refactor/axiosDefaultHeader : axios의 헤더를 axiosInstance파일에서 defaultHeader로 설정
  json-server/db.json
  src/Common/axiosInstance.js
  src/Components/Navbar/Navbar.js
  src/Components/auth/AuthProvider.js
  src/Components/auth/RegisterForm.js
Labels: refactor

#49 [#48] geolocation 이용하여 현재 위치 좌표 알아내기
  src/Hooks/useGetGeolocation.jsx
  src/Pages/MainPage/MainPage.jsx
Labels: enhancement

#51 [#12] feature/myPage/reviewList 리뷰수정 후 데이터 유지
  src/Components/MyPage/MyReviews/MyReviews.js
  src/Components/MyPage/MyReviews/MyReviews.styles.js
  src/Components/MyPage/MyReviews/MyReviewsLayout.js
Labels: bug, design

#53 [#52] feature/mainPage/recommend 내 근처캠핑장 추천 section 슬라이드로 변경
  json-server/db.json
  src/Components/Main/MainCampRecommend/MainCampRecommend.js
  src/Components/Main/MainCampRecommend/MainCampRecommend.styles.js
Labels: design

#55 [#54] Feature/API 백엔드 api 통신
  cors.json
  package.json
  src/Components/CampInformation/CampInformation.style.js
  src/Components/ImageUpload/ImagePreview/ImagePreview.jsx
  src/Components/Main/MainBestReview/MainBestReview.js
  src/Components/Main/MainCampRecommend/MainCampRecommend.js
  src/Components/Modal/DeleteModal.js
  src/Components/MyPage/AlrimList/AlrimLayout.js
  src/Components/MyPage/AlrimList/AlrimList.js
  src/Components/MyPage/LikesList/LikeListLayout.js
  src/Components/MyPage/LikesList/LikesList.js
  src/Components/MyPage/MyReviews/MyReviews.js
  src/Components/MyPage/MyReviews/MyReviewsLayout.js
  src/Components/Navbar/Navbar.js
  src/Components/SearchBar/SearchBar.jsx
  src/Components/auth/AuthProvider.js
  src/Components/auth/RegisterForm.js
  src/Pages/DetailPage/DetailPage.jsx
  src/Pages/DetailPage/DetailPage.style.js
  src/Pages/MainPage/MainPage.jsx
  src/Pages/MyPage/MyPage.js
  src/Pages/SearchPage/SearchPage.js
  src/Service/camps.js
  src/setupProxy.js
Labels: refactor

#56 #6 feat: 후기 작성,수정,삭제 기능 개발
  src/Components/CampReview/CampReview.jsx
  src/Components/CampReview/CampReview.style.js
  src/Components/Modal/DeleteModal.js
  src/Components/MyPage/MyReviews/MyReviewsLayout.js
  src/Components/Review/Review.jsx
  src/Components/Review/Review.style.js
  src/Components/Review/ReviewsList.jsx
  src/Components/Review/ReviewsList.styles.js
  src/Pages/DetailPage/DetailPage.jsx
  src/Pages/MyPage/MyPage.js
  src/Service/camps.js
Labels: enhancement

#59 #58 feat: 유저가 작성한 리뷰만 수정, 삭제 버튼이 렌더링
  src/Components/Review/Review.jsx
  src/Components/Review/ReviewsList.jsx
  src/Components/Review/ReviewsList.styles.js
  src/Service/camps.js
Labels: enhancement

#61 [#60]Feature/reviewLike 리뷰 좋아요 기능 및 UI
  src/Components/Review/ReviewsList.jsx
  src/Components/Review/ReviewsList.styles.js
  src/Service/camps.js
Labels: enhancement, design

#62 [#50] Feature/detailPageResponsive
  json-server/db.json
  src/Components/CampInformation/CampInformation.style.js
  src/Components/CampLocation/CampLocation.jsx
  src/Components/CampLocation/CampLocation.style.js
  src/Pages/DetailPage/DetailPage.jsx
  src/Pages/DetailPage/DetailPage.style.js
Labels: design

#63 [#52] [#57] feature/slide 메인페이지 내 근처 캠핑장 추천 반응형디자인 & 슬라이드 기능 추가
  src/Components/CampInformation/CampInformation.jsx
  src/Components/CampInformation/CampInformation.style.js
  src/Components/Main/MainCampRecommend/MainCampRecommend.js
  src/Components/Main/MainCampRecommend/MainCampRecommend.styles.js
  src/Components/MyPage/AlrimList/AlrimLayout.js
  src/Components/Notice/Notice.jsx
  src/Components/Notice/Notice.style.jsx
  src/Pages/DetailPage/DetailPage.jsx
Labels: enhancement, design

#66 [#65] Feature/onlyLoginAccess 로그인 안된 유저 마이페이지 접근 제한
  src/Components/auth/AuthProvider.js
  src/Pages/MyPage/MyPage.js
Labels: enhancement

#67 [#35] Feature/reviewPagination 리뷰 페이지네이션 기능
  src/Components/Review/Review.jsx
  src/Components/Review/Review.style.js
  src/Components/Review/ReviewsList.jsx
  src/Pages/DetailPage/DetailPage.jsx
  src/Service/camps.js
Labels: enhancement

#71 [#14][#69][#70] Feature/authRefactor 로그인 관련 이슈 해결 및 리팩토링
  src/Common/axiosInstance.js
  src/Components/Modal/DeleteModal.js
  src/Components/Modal/Modal.jsx
  src/Components/Modal/Modal.style.js
  src/Components/Navbar/Navbar.js
  src/Components/Review/Review.jsx
  src/Components/Review/Review.style.js
  src/Components/Review/ReviewsList.jsx
  src/Components/SearchBar/SearchBar.jsx
  src/Components/auth/AuthProvider.js
  src/Components/auth/RegisterForm.js
  src/Pages/SearchPage/SearchPage.js
  src/Service/firebaseAuth.js
Labels: bug, enhancement, refactor

#72 [#68] Feature/searchPageDesign 검색페이지 반응형 디자인
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/Navbar.styles.js
  src/Components/SearchBar/ResultList/ResultList.jsx
  src/Components/SearchBar/SearchBar.jsx
  src/Components/SearchBar/SearchBar.style.js
  src/Components/SearchBar/SearchResult/SearchResult.jsx
  src/Components/SearchLocation/SearchLocation.jsx
  src/Pages/SearchPage/SearchPage.js
  src/Service/camps.js
Labels: refactor, design

#73 [#36] Feature/search page/filtering
  src/Common/AddressData.js
  src/Components/Main/MainSearch/MainSearch.js
  src/Components/SearchBar/ResultList/ResultList.jsx
  src/Components/SearchBar/SearchBar.jsx
  src/Components/SearchBar/SearchBar.style.js
  src/Components/SearchBar/SearchResult/SearchResult.jsx
  src/Components/SearchLocation/EventMarker/EventMarker.jsx
  src/Components/SearchLocation/SearchLocation.jsx
  src/Pages/SearchPage/SearchPage.js
  src/Service/camps.js
Labels: enhancement

#74 [#35] feature/searchPagination 검색페이지 페이지네이션 구현
  src/Components/SearchBar/SearchBar.jsx
  src/Components/SearchBar/SearchResult/SearchResult.jsx
  src/Components/SearchLocation/SearchLocation.jsx
  src/Pages/SearchPage/SearchPage.js
  src/Service/camps.js
  src/context/SearchPaginationContext.js
Labels: enhancement

#76 [#13]Feature/myPage/alrim 마이페이지 알림기능
  src/Components/MyPage/AlrimList/Alrim.js
  src/Components/MyPage/AlrimList/AlrimLayout.js
  src/Components/MyPage/AlrimList/AlrimList.js
  src/Components/MyPage/AlrimList/AlrimList.styles.js
  src/Service/camps.js
Labels: enhancement

#79 [#11]Feature/myPage/likeList 좋아요한 캠핑장 리스트
  src/Components/MyPage/LikesList/LikeCamp.js
  src/Components/MyPage/LikesList/LikeListLayout.js
  src/Components/MyPage/LikesList/LikesList.js
  src/Components/MyPage/LikesList/LikesList.styles.js
  src/Service/camps.js
Labels: enhancement

#82 [#2] Feature/nearCamp 가까운 캠핑장 추천 기능
  src/Components/Main/MainCampRecommend/MainCampRecommend.js
  src/Components/Main/MainCampRecommend/MainCampRecommend.styles.js
  src/Components/Main/MainCampRecommend/NearCamp/NearCamp.jsx
  src/Components/Main/MainCampRecommend/NearCamp/NearCamp.style.js
  src/Components/Main/MainSearch/MainSearch.js
  src/Components/SearchBar/SearchBar.jsx
  src/Components/SearchBar/SearchResult/SearchResult.jsx
  src/Hooks/useGetGeolocation.jsx
  src/Pages/MainPage/MainPage.jsx
  src/Service/camps.js
Labels: enhancement

#86 [#85] Feature/community 커뮤니티 페이지 이동시 개발중이라고 알림
  src/App.js
  src/Components/Navbar/Navbar.js
  src/Pages/CommunityPage/CommunityPage.jsx
Labels: enhancement, design

#88 [#83] Feature/skeleton 데이터를 받아와 렌더링하는 곳에 Skeleton UI 추가
  src/Components/Main/MainCampRecommend/MainCampRecommend.js
  src/Components/Main/MainCampRecommend/MainCampRecommend.styles.js
  src/Components/Main/MainCampRecommend/NearCamp/NearCamp.jsx
  src/Components/MyPage/LikesList/LikeListLayout.js
  src/Components/MyPage/LikesList/LikesList.js
  src/Components/Review/Review.jsx
  src/Components/SearchBar/SearchResult/SearchResult.jsx
  src/Components/Skeleton/LikeSkeleton.jsx
  src/Components/Skeleton/RecommendSkeleton.jsx
  src/Components/Skeleton/ReviewSkeleton.jsx
  src/Components/Skeleton/SearchSkeleton.jsx
  src/Components/Skeleton/Shimmer.jsx
Labels: enhancement, design

#89 [#87]Feature/myPage/alrim avatar에 안읽은 알림 갯수 badge 추가 & 날짜 변환 customHook
  package-lock.json
  package.json
  src/Components/MyPage/AlrimList/Alrim.js
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/Navbar.styles.js
  src/Hooks/useGetDate.js
  yarn.lock
Labels: enhancement, design

#93 [#92]Feature/mobileCloseMenu 모바일 뱃지 위치 수정
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/Navbar.styles.js
Labels: design

#95 [#94] feature/rateStar allowHalf props 제거
  src/Components/Review/ReviewsList.jsx
  src/Pages/DetailPage/DetailPage.jsx
Labels: refactor

#97 [#96]Feature/reviewMobileDesign 모바일 리뷰컴포넌트 디자인 수정
  src/Components/Review/Review.style.js
  src/Components/Review/ReviewsList.jsx
  src/Components/Review/ReviewsList.styles.js
Labels: refactor, design

#100 [#99] Feature/antdCustom AntDesign Primary Color 변경
  public/index.html
  src/App.js
  src/Pages/SearchPage/SearchPage.js
  src/Styles/antdCustom.css
Labels: refactor

#103 [#102]Feature/reviewStyle 텍스트 길어질 때 review 스타일 수정
  src/Components/Review/ReviewsList.styles.js
Labels: enhancement, refactor, design

#105 [#104] Feature/readMore 리뷰 길이에 따라 더보기, 접기 버튼 활성화
  src/Components/Review/Review.jsx
  src/Components/Review/ReviewsList.jsx
  src/Components/Review/ReviewsList.styles.js
Labels: enhancement

#109 [#108] Feature/layoutRefactor 레이아웃 리팩토링 및 정렬 별점순으로 수정
  README.md
  src/components/review/reveiwList/ReviewsList.jsx
  src/components/review/reveiwList/reviewsList.styles.js
  src/pages/myPage/MyPage.jsx
  src/pages/searchPage/searchBar/SearchBar.jsx
  src/pages/searchPage/searchBar/resultList/ResultList.jsx
  src/pages/searchPage/searchBar/resultList/ResultList.style.js
  src/pages/searchPage/searchBar/searchResult/searchResult/SearchResult.jsx
  src/pages/searchPage/searchBar/searchResult/searchResult/searchResult.style.js
  src/service/api.js
Labels: refactor
